Improve help and handling of args.

diff --git a/sysinfo b/sysinfo
--- a/sysinfo
+++ b/sysinfo
@@ -1,7 +1,10 @@
 #!/bin/bash
 # vi: se fdm=marker
 
-VERSION=0.1
+SCRIPT_FILE=$(basename $0)
+SCRIPT_DIR=$(dirname $0)
+
+VERSION=1.0
 NO=no
 YES=yes
 DEBUG=0
@@ -38,30 +41,34 @@ function get_platform {
 ################################################################
 
 function print_help {
-	echo "Usage: sysinfo [options]"
-	echo
-	echo "Options:"
-	echo "   -a, --audio             Print audio volume information."
-	echo "   -b, --battery           Display battery information."
-	echo "   -c, --coloring          Enable coloring of output."
-	echo "   -g, --debug             Debug mode."
-	echo "       --decbright         Decrease screen brightness."
-	echo "       --decvol            Decrease audio volume."
-	echo "   -h, --help              Print this help message."
-	echo "       --incbright         Increase screen brightness."
-	echo "       --incvol            Increase audio volume."
-	echo "   -l, --oneline           Print information on one line only."
-	echo "       --micmute           Mute/unmute microphone."
-	echo "       --mute              Mute/unmute audio."
-	echo "   -m, --micro             Print micro information."
-	echo "   -n, --network           Display network information."
-	echo "       --no-tags           Do not use tags as prefix of information."
-	echo "   -o, --order             Set order of information display. Default is $ORDER."
-	echo "   -s, --screen            Print screen brightness information."
-	echo "       --switch-audio-sink Switch of audio sink."
-	echo "       --shorten-msgs      Shorten messages."
-	echo "   -v, --vpn               Print VPN connection status."
-	echo "   -x, --xmobar            Output for xmobar."
+cat <<END_HELP_MSG
+$SCRIPT, version $VERSION, displays system information for user on command line or on xmobar status bar.
+
+Usage: $SCRIPT_FILE [options]
+
+Options:
+   -a, --audio             Print audio volume information.
+   -b, --battery           Display battery information.
+   -c, --coloring          Enable coloring of output.
+   -g, --debug             Debug mode.
+       --decbright         Decrease screen brightness.
+       --decvol            Decrease audio volume.
+   -h, --help              Print this help message.
+       --incbright         Increase screen brightness.
+       --incvol            Increase audio volume.
+   -l, --oneline           Print information on one line only.
+       --micmute           Mute/unmute microphone.
+       --mute              Mute/unmute audio.
+   -m, --micro             Print micro information.
+   -n, --network           Display network information.
+       --no-tags           Do not use tags as prefix of information.
+   -o, --order             Set order of information display. Default is $ORDER.
+   -s, --screen            Print screen brightness information.
+       --switch-audio-sink Switch of audio sink.
+       --shorten-msgs      Shorten messages.
+   -v, --vpn               Print VPN connection status.
+   -x, --xmobar            Output for xmobar.
+END_HELP_MSG
 }
 
 # Error {{{1
@@ -71,7 +78,7 @@ function error {
 
 	local msg=$1
 
-	echo "ERROR: $msg" >&2
+	echo "[ERROR] $msg" >&2
 
 	exit 1
 }
@@ -198,9 +205,7 @@ function read_args {
 			   --mute)      MUTE=$YES ;;
 			   --micmute)   MICMUTE=$YES ;;
 			   --no-tags)   TAGS=$NO ;;
-			-)              error "Illegal option $1." ;;
-			--)             error "Illegal option $1." ;;
-			--*)            error "Illegal option $1." ;;
+			-|--|--*)       error "Illegal option $1." ;;
 			-?)             error "Unknown option $1." ;;
 			-[^-]*)         split_opt=$(echo $1 | sed 's/^-//' | sed 's/\([a-zA-Z]\)/ -\1/g') ; set -- $1$split_opt "${@:2}" ;;
 			*) break
